### ISSUE TITLE
Is this being worked on?

### ISSUE THREAD

**Issue by spences10** [petercr/YouTube-Project#1]
Hey @petercr is there anything happening with this now?

**Comment by petercr** [comment]
@spences10 I've been talking with Tim on Slack about this project and getting it going. We were originally thinking about going with React, but neither of us know it very well. I think we might just go with a _framework _ instead and just make a static site first. **Then** redo the project at some point later with React. 😄 😉

**Comment by timOTdev** [comment]
@spences10 @petercr I'm picking up React right now through some courses. The first iteration of the site can just work with the Youtube API and Materialize.

**Comment by spences10** [comment]
Did neither of you feel confident looking at @amandeepmittal's project here: https://github.com/amandeepmittal/react-youtube-search?

He usually has really well documented code and from the looks of it, it was made with create react app so it should be nicely structured.

**Comment by amandeepmittal** [comment]
If you need help, I can help with the code.

**Comment by petercr** [comment]
Thanks @amandeepmittal I've been busy over the last few days, but @timh1203 and I have been working on it. And he got the `fetch()` working for the API data ✨ 

But if we run into any issues then I'l be sure to let you know 😃

**Comment by spences10** [comment]
Cool 😎 

I close this now

Thanks
